site:
  # each line is a partition (Raft group), first 3 sites are replicas (no learner in Raft)
  server:
    - ["s101:7001", "s201:7101", "s301:7201"]
    - ["s102:7002", "s202:7102", "s302:7202"]

# s101: localhost
# s201: p1
# s301: p2
process:
  s101: localhost
  s201: p1
  s301: p2
  s102: localhost
  s202: p1
  s302: p2

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  p1: 127.0.0.1
  p2: 127.0.0.1
