# Luigi 2-Shard Local Test Configuration
# Compatible with janus::Config parser

site:
  server:
    - ["s0:31850"]   # Shard 0
    - ["s1:31851"]   # Shard 1
  client:
    - ["c0"]

process:
  s0: localhost
  s1: localhost
  c0: localhost

host:
  localhost: 127.0.0.1
