# Luigi 1-Shard Local Test Configuration
# Compatible with janus::Config parser

# site - partition map
# Each line is a partition (shard)
site:
  server:
    - ["s101:31850"]   # Shard 0 leader
  client:
    - ["c101"]

# site_name -> process_name map
process:
  s101: localhost
  c101: localhost

# process_name -> host_addr map
host:
  localhost: 127.0.0.1
