site:
  server:
    - ["localhost:38100", "p1:38101", "p2:38102"]
  client:
    - ["c01"]

process:
  localhost: localhost
  p1: p1
  p2: p2
  c01: client

host:
  localhost: 127.0.0.1
  p1: 127.0.0.1
  p2: 127.0.0.1
  client: 127.0.0.1
