

site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:18000", "s201:18001", "s301:18002"]
  client: # each line is a partition
    - ["c000", "c001", "c002", "c003", "c004", "c005", "c006", "c007", "c008", "c009",
      "c010", "c011", "c012", "c013", "c014", "c015", "c016", "c017", "c018", "c019",
      "c020", "c021", "c022", "c023", "c024", "c025", "c026", "c027", "c028", "c029",
      "c030", "c031", "c032", "c033", "c034", "c035", "c036", "c037", "c038", "c039",]

process:
  s101: localhost
  s201: localhost
  s301: localhost
  
  c000: localhost
  c001: localhost
  c002: localhost
  c003: localhost
  c004: localhost
  c005: localhost
  c006: localhost
  c007: localhost
  c008: localhost
  c009: localhost

  c010: localhost
  c011: localhost
  c012: localhost
  c013: localhost
  c014: localhost
  c015: localhost
  c016: localhost
  c017: localhost
  c018: localhost
  c019: localhost

  c020: localhost
  c021: localhost
  c022: localhost
  c023: localhost
  c024: localhost
  c025: localhost
  c026: localhost
  c027: localhost
  c028: localhost
  c029: localhost

  c030: localhost
  c031: localhost
  c032: localhost
  c033: localhost
  c034: localhost
  c035: localhost
  c036: localhost
  c037: localhost
  c038: localhost
  c039: localhost

host:
  localhost: 127.0.0.1