
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:18000", "s201:18001", "s301:18002", "s401:18003", "s501:18004"]
  client: # each line is a partition
    - ["c101", "c201", "c301", "c401", "c501"]

process:
  s101: localhost
  s201: localhost
  s301: localhost
  s401: localhost
  s501: localhost
  c101: localhost
  c201: localhost
  c301: localhost
  c401: localhost
  c501: localhost

host:
  localhost: 127.0.0.1