

site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:38000", "s201:38001", "s301:38002", "s401:38003", "s501:38004"]
  client: # each line is a partition
    - ["c01", "c02", "c03", "c04", "c05",
       "c06", "c07", "c08", "c09", "c10",
       "c11", "c12", "c13", "c14", "c15",
       "c16", "c17", "c18", "c19", "c20",
       "c21", "c22", "c23", "c24", "c25",
       "c26", "c27", "c28", "c29", "c30",
       "c31", "c32", "c33", "c34", "c35",
       "c36", "c37", "c38", "c39", "c40",
       "c41", "c42", "c43", "c44", "c45",
       "c46", "c47", "c48", "c49", "c50",
       "c51", "c52", "c53", "c54", "c55",
       "c56", "c57", "c58", "c59", "c60",]


process:
  s101: aws0
  s201: aws1
  s301: aws2
  s401: aws3
  s501: aws4
  c01: aws0
  c02: aws1
  c03: aws2
  c04: aws3
  c05: aws4
  c06: aws5
  c07: aws6
  c08: aws7
  c09: aws8
  c10: aws9
  c11: aws0
  c12: aws1
  c13: aws2
  c14: aws3
  c15: aws4
  c16: aws5
  c17: aws6
  c18: aws7
  c19: aws8
  c20: aws9
  c21: aws0
  c22: aws1
  c23: aws2
  c24: aws3
  c25: aws4
  c26: aws5
  c27: aws6
  c28: aws7
  c29: aws8
  c30: aws9
  c31: aws0
  c32: aws1
  c33: aws2
  c34: aws3
  c35: aws4
  c36: aws5
  c37: aws6
  c38: aws7
  c39: aws8
  c40: aws9
  c41: aws0
  c42: aws1
  c43: aws2
  c44: aws3
  c45: aws4
  c46: aws5
  c47: aws6
  c48: aws7
  c49: aws8
  c50: aws9
  c51: aws0
  c52: aws1
  c53: aws2
  c54: aws3
  c55: aws4
  c56: aws5
  c57: aws6
  c58: aws7
  c59: aws8
  c60: aws9
  
  
host:
  aws0: 184.72.49.232
  aws1: 16.163.96.221
  aws2: 54.253.53.26
  aws3: 18.198.73.192
  aws4: 18.229.52.109
  aws5: 44.205.230.205
  aws6: 3.6.253.80
  aws7: 52.195.138.239
  aws8: 52.60.216.121
  aws9: 35.179.49.225