
# config/rw.yml 
bench:
  workload: rw
  scale: 1
  weight:
    read: 0 
    write: 1
  population: # intial number of records in each table
    history: 1000000

schema: # table information
  - name: history
    column:
      - {name: h_key,     type: integer, primary: true}
      - {name: h_c_id,    type: integer}

# sharding strategy.
# default is MOD by primary key.
# CUSTOM means strategy is defined in the code.
# TODO a better way to define sharding strategy.
sharding:
  history:    MOD

# config/occ_paxos.yml
mode:
  cc: curp # concurrency control
  ab: multi_paxos_plus # atomic broadcast
  read_only: occ
  batch: false
  retry: 20
  ongoing: 1 # per client

# config/concurrent_100.yml 
n_concurrent: 50

# config/1c1s3r1p.yml
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:38000", "s201:38001", "s301:38002"]
  client: # each line is a partition
    # - ["c01", "c02", "c03"]
    - ["c01", "c02", "c03", "c04", "c05", "c06", "c07", "c08", "c09", "c10"]

# site_name - process_name map
process:
  s101: localhost 
  s201: localhost 
  s301: localhost 
  c01: localhost
  c02: localhost
  c03: localhost
  c04: localhost
  c05: localhost
  c06: localhost
  c07: localhost
  c08: localhost
  c09: localhost
  c10: localhost

host:
  localhost: 127.0.0.1